version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: urlshortener-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: postgres -c logging_collector=on -c log_statement=all -c log_directory=/var/log/postgresql

volumes:
  postgres_data:
    driver: local