packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - esbuild
  - prisma

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@swc/core'
  - core-js
  - sharp
